swagger: '2.0'
info:
  version: 1.0.0
  title: Login Page
  description: Login

paths:
  /Login_Page:
    get:
      summary: Login here to continue
      description: Please provide your credentials to log in.
      parameters:
        - name: username
          in: query
          description: The username for login
          required: true
          type: string
        - name: password
          in: query
          description: The password for login
          required: true
          type: string
      tags:
        - Click here to login
      responses:
        '200':
          description: Successfully logged in and authenticated.
        '400':
          description: Invalid credentials or missing parameters.
        '500':
          description: Internal server error.
